Algoritmo "Ex_04"
// 
//  
// Descrição   : Desenvolva um algoritmo que leia dois números inteiros e mostre o somatório
// entre eles.
// Autor(a)    : Pedro H A Gabriel
// Data atual  : 20/03/2023
Var
n1, n2, soma: inteiro


Inicio
Escreva("Digite o primeiro valor a ser somado: ")
leia(n1)
Escreva("Digite o segundo valor a ser somado: ")
leia(n2)

soma <- n1 + n2

Escreva("A soma entre ", n1, " e ", n2, " é igual a ", soma)

Fimalgoritmo