Algoritmo "Ex_03"
// 
//  
// Descrição   : Crie um programa que leia o nome e o salário de um funcionário, mostrando no
// final uma mensagem.
// Autor(a)    : Pedro H Almeida Gabriel
// Data atual  : 20/03/2023
Var
nomeFunc: caractere
salarioFunc: real


Inicio
Escreval("Qual o nome do funcionário?")
leia(nomeFunc)
Escreval("Qual o salário do funcionário ", nomeFunc, " ?")
leia(salarioFunc)

Escreva()
Escreva("O salário do funcionário ", nomeFunc, " é R$", salarioFunc )


Fimalgoritmo