Algoritmo "EX_20"
//
//
// Descrição   : Desenvolva um programa que leia um número inteiro e mostre se ele é PAR ou
// ÍMPAR.
// Autor(a)    : Pedro H
// Data atual  : 19/04/2023
Var
   N1 : inteiro


Inicio
   escreval("Digite um número: ")
   leia(N1)

   se(N1%2 = 0) entao
   
      escreval("O número ", N1, " é par" )

   senao

      escreval("O número ", N1, " é impar" )
      
   fimse


Fimalgoritmo