Algoritmo "EX_45"
//
//
// Descrição   : Crie um programa que calcule e mostre na tela o resultado da soma entre 6 +
// 8 + 10 + 12 + 14 + ... + 98 + 100.
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/05/2023
Var

   i, soma : inteiro


Inicio

   i <- 6

   Enquanto (i<=100) faca

      Escreva(i," +")

      soma <- soma + i
      i <- i + 2
      
   fimEnquanto
   
   escrevaL("")
   escrevaL("")
   escrevaL("O resultado da soma dos valores é ",soma)




Fimalgoritmo