Algoritmo "EX_48"

// Descrição   : Faça um programa que leia 7 números inteiros e no final mostre o somatório
// entre eles.

// Autor(a)    : Pedro H
// Data atual  : 08/05/2023

Var
cont, valor, soma: inteiro

Inicio

cont <- 1
enquanto (cont<=7) faca

Escreva("Digite o ", cont, "o valor: ")
leia(valor)

soma<- soma+valor
cont <- cont + 1

fimEnquanto

EscrevaL("A somatorio dos valores é ", soma)


Fimalgoritmo