Algoritmo "EX_66"

// Descrição   : Escreva um programa que leia um número qualquer e mostre a tabuada desse
// número, usando a estrutura “para”.
// Ex: Digite um valor: 5
// 5 x 1 = 5
// 5 x 2 = 10
// 5 x 3 = 15 ...

// Autor(a)    : Pedro H
// Data atual  : 22/05/2023
Var

I , Res, N : inteiro


Inicio

Escreva("Digite um valor para ver tabuada: ")
leia(N)

Para I de 1 ate 10 faca

Res <- I * N

Escreval( N, " x", I, "=", Res )

FimPara


Fimalgoritmo