Algoritmo "EX_67"

// Descrição   : Faça um programa usando a estrutura “para” que leia um número inteiro
// positivo e mostre na tela uma contagem de 0 até o valor digitado:
// Ex: Digite um valor: 9
// Contagem: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, FIM!
// Autor(a)    : Pedro H
// Data atual  : 22/05/2023

Var
V, Cont : inteiro


Inicio

Escreva("Digite um valor: ")
leia(V)

Escreva("Contagem: ")
Para Cont de 0 ate V faca

Escreva(Cont)

FimPara

Escreva(" FIM !!")

Fimalgoritmo