Algoritmo "EX_71"

// Descrição   : Faça um programa que preencha automaticamente um vetor numérico com 8
// posições, conforme abaixo:
//999 999 999 999 999 999 999 999
// 0   1   2   3   4   5   6   7
// Autor(a)    : Pedro H
// Data atual  : 25/05/2023

Var

V: vetor[0..7] de inteiro
i: inteiro

Inicio



Para i <- 0 ate 7 faca

V[i] <- 999
Escreva(V[i], " ")

FimPara


Fimalgoritmo